# Generated by Django 5.0.6 on 2024-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_delete_status_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='No description provided', max_length=255),
        ),
    ]
