# Generated by Django 5.0.6 on 2024-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
